
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.HPaned hpaned1;

	private global::Gtk.VBox vbox1;

	private global::Gtk.Image hangmanImage;

	private global::Gtk.Label wordText;

	private global::Gtk.VBox vbox3;

	private global::Gtk.TextView resultText;

	private global::Gtk.Label guessesRemaining;

	private global::Gtk.Label gameOverText;

	private global::Gtk.HBox hbox1;

	private global::Gtk.Entry inputText;

	private global::Gtk.Button enterButton;

	private global::Gtk.Button quitButton;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("Hangman");
		this.Icon = global::Gdk.Pixbuf.LoadFromResource("HangmanGame.Resources.images.program_icon.png");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.AllowShrink = true;
		this.DefaultWidth = 800;
		this.DefaultHeight = 475;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.hpaned1 = new global::Gtk.HPaned();
		this.hpaned1.CanFocus = true;
		this.hpaned1.Name = "hpaned1";
		this.hpaned1.Position = 350;
		// Container child hpaned1.Gtk.Paned+PanedChild
		this.vbox1 = new global::Gtk.VBox();
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hangmanImage = new global::Gtk.Image();
		this.hangmanImage.Name = "hangmanImage";
		this.vbox1.Add(this.hangmanImage);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hangmanImage]));
		w1.Position = 1;
		w1.Expand = false;
		w1.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.wordText = new global::Gtk.Label();
		this.wordText.Name = "wordText";
		this.vbox1.Add(this.wordText);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.wordText]));
		w2.Position = 2;
		w2.Fill = false;
		this.hpaned1.Add(this.vbox1);
		global::Gtk.Paned.PanedChild w3 = ((global::Gtk.Paned.PanedChild)(this.hpaned1[this.vbox1]));
		w3.Resize = false;
		// Container child hpaned1.Gtk.Paned+PanedChild
		this.vbox3 = new global::Gtk.VBox();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.resultText = new global::Gtk.TextView();
		this.resultText.Buffer.Text = global::Mono.Unix.Catalog.GetString("Awaiting your attempt...");
		this.resultText.Name = "resultText";
		this.resultText.Editable = false;
		this.resultText.CursorVisible = false;
		this.resultText.Justification = ((global::Gtk.Justification)(2));
		this.resultText.WrapMode = ((global::Gtk.WrapMode)(2));
		this.vbox3.Add(this.resultText);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.resultText]));
		w4.Position = 0;
		// Container child vbox3.Gtk.Box+BoxChild
		this.guessesRemaining = new global::Gtk.Label();
		this.guessesRemaining.Name = "guessesRemaining";
		this.guessesRemaining.LabelProp = global::Mono.Unix.Catalog.GetString("Guesses Remaining: 6");
		this.vbox3.Add(this.guessesRemaining);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.guessesRemaining]));
		w5.Position = 1;
		w5.Expand = false;
		w5.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.gameOverText = new global::Gtk.Label();
		this.gameOverText.Name = "gameOverText";
		this.gameOverText.LabelProp = global::Mono.Unix.Catalog.GetString("GAME OVER!!!");
		this.vbox3.Add(this.gameOverText);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.gameOverText]));
		w6.Position = 2;
		w6.Expand = false;
		w6.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.inputText = new global::Gtk.Entry();
		this.inputText.CanFocus = true;
		this.inputText.Name = "inputText";
		this.inputText.IsEditable = true;
		this.inputText.InvisibleChar = '•';
		this.hbox1.Add(this.inputText);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.inputText]));
		w7.Position = 0;
		// Container child hbox1.Gtk.Box+BoxChild
		this.enterButton = new global::Gtk.Button();
		this.enterButton.CanFocus = true;
		this.enterButton.Name = "enterButton";
		this.enterButton.UseStock = true;
		this.enterButton.UseUnderline = true;
		this.enterButton.Label = "gtk-ok";
		this.hbox1.Add(this.enterButton);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.enterButton]));
		w8.Position = 1;
		w8.Expand = false;
		w8.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.quitButton = new global::Gtk.Button();
		this.quitButton.CanFocus = true;
		this.quitButton.Name = "quitButton";
		this.quitButton.UseStock = true;
		this.quitButton.UseUnderline = true;
		this.quitButton.Label = "gtk-quit";
		this.hbox1.Add(this.quitButton);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.quitButton]));
		w9.Position = 2;
		w9.Expand = false;
		w9.Fill = false;
		this.vbox3.Add(this.hbox1);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox1]));
		w10.Position = 3;
		w10.Expand = false;
		w10.Fill = false;
		this.hpaned1.Add(this.vbox3);
		this.Add(this.hpaned1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.gameOverText.Hide();
		this.quitButton.Hide();
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.inputText.Activated += new global::System.EventHandler(this.OnEnter);
		this.enterButton.Clicked += new global::System.EventHandler(this.OnEnter);
		this.quitButton.Clicked += new global::System.EventHandler(this.OnQuit);
	}
}
